package elpoli.com;

import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;

import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

public class FramePolF2 extends javax.swing.JFrame implements ChangeListener {

    PolF2 A, B, C;

    public FramePolF2() {
        initComponents();
        jScrollPane1.getViewport().addChangeListener(this);
        A = new PolF2("A");
        B = new PolF2("B");
        C = new PolF2("C");
        repaint();
    }

    public void stateChanged(ChangeEvent g) {
        repaint();
    }

    public void paint(Graphics g) {
        super.paint(g);
        Graphics g1;
        g1 = jScrollPane1.getViewport().getGraphics();
        Font fuente = new Font("Tymes Roman", Font.BOLD, 18);
        g1.setFont(fuente);

        int posC = 100 - jScrollPane1.getViewport().getViewPosition().x;
        int posF = 10 - jScrollPane1.getViewport().getViewPosition().y;
        g1.setColor(Color.black);

        if (A != null) {
            A.pintar(g1, posC, posF);

        }
        if (B != null) {
            B.pintar(g1, posC, posF + 120);
        }
        if (C != null) {
            C.pintar(g1, posC, posF + 240);
        }

    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();//Polinomio A
        jButton3 = new javax.swing.JButton();// Polinomio B
        jButton4 = new javax.swing.JButton();// Poliinomio A+B=C
        jButton5 = new javax.swing.JButton();// multiplicar
        jButton6 = new javax.swing.JButton();// Eliminar termino en A
        jButton7 = new javax.swing.JButton();// Eliminar termino en B

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("POLINOMIOS REPRESENTADOS COMO VECTOR FORMA 2");
        setAlwaysOnTop(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(5000, 3000));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 5000, Short.MAX_VALUE));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 3000, Short.MAX_VALUE));

        jScrollPane1.setViewportView(jPanel1);

        jButton2.setText("INSERTAR TERMINO EN A");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("INSERTAR TERMINO EN B");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jButton4.setText("C=A+B");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jButton5.setText("C=AxB");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jButton6.setText("Eliminar termino A");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jButton7.setText("Eliminar termino B");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jButton1.setText("REDIMENSIONAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 132,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jButton2)
                                                .addGap(18, 18, 18) // Espacio entre los botones
                                                .addComponent(jButton3) // Botón para llenar polinomio B
                                                .addGap(18, 18, 18)
                                                .addComponent(jButton4)// Boton Sumar
                                                .addGap(18, 18, 18)
                                                .addComponent(jButton5)// Boton Multiplicar
                                                .addGap(18, 18, 18))
                                        .addComponent(jButton6)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton7)
                                        .addGap(18, 18, 18)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 971,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 417,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButton1)
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 23,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton3)
                                        .addComponent(jButton4)
                                        .addComponent(jButton5)

                                )
                                .addGap(29, 29, 29)
                                .addComponent(jButton6)
                                .addGap(18,18,18)
                                .addComponent(jButton7)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // *Action Performed */

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {// Accion de polinomio A

        String entrada;

        int coe = 0;
        int exp = 0;
        coe = Integer.parseInt(JOptionPane.showInputDialog(this, "ingrese el coeficiente de A"));
        exp = Integer.parseInt(JOptionPane.showInputDialog(this, "ingrese el exponente de A"));
        A.insertarTermino(coe, exp);
        repaint();
    }

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {// Accion de polinomio B

        String entrada;

        int coe = 0;
        int exp = 0;
        coe = Integer.parseInt(JOptionPane.showInputDialog(this, "ingrese el coeficiente de B"));
        exp = Integer.parseInt(JOptionPane.showInputDialog(this, "ingrese el exponente de B"));
        B.insertarTermino(coe, exp);
        repaint();
    }

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {// Accion de sumar Poliniomios

        C = A.sumar(B);

        repaint();
    }

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {

        C = A.multiplicar(B);
        repaint();

    }

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {

        int expo=0;

        expo=Integer.parseInt(JOptionPane.showInputDialog(this, "ingrese el exponente del coeficiente a eliminar"));

        A.eliminacion(expo);
        repaint();

    }

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {
        int expo=0;

        expo=Integer.parseInt(JOptionPane.showInputDialog(this, "ingrese el exponente del coeficiente a eliminar"));

        B.eliminacion(expo);
        repaint();

    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// Accion de Redimensionar
        String entrada;
        boolean terminado = false;
        int cantidad = 0;
        do {
            entrada = JOptionPane.showInputDialog(this, "ingrese la cantidad a redimensionar  [ -3, 3]");

            if (entrada != null) {
                try {
                    cantidad = Integer.parseInt(entrada);
                    if (cantidad < -3 || cantidad > 3) {
                        JOptionPane.showMessageDialog(this, "debe ingresar un entero entre [ -3, 3]");
                    } else {
                        terminado = true;
                    }
                } catch (NumberFormatException x) {
                    JOptionPane.showMessageDialog(this, "la cantidad ingresada debe ser numerica");
                }
            }

        } while (terminado == false && entrada != null);
        if (terminado == true) {
            A.redimensionar(cantidad);
            repaint();
        }
    }// GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FramePolF2.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FramePolF2.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FramePolF2.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FramePolF2.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new FramePolF2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;//Redimensionar
    private javax.swing.JButton jButton2;//Polinomio A
    private javax.swing.JButton jButton3;// Polinomio B
    private javax.swing.JButton jButton4;// Suma polinomio A+B=C
    private javax.swing.JButton jButton5;// Multiplicacion AxB=C
    private javax.swing.JButton jButton6;// Eliminar termino en A
    private javax.swing.JButton jButton7;// Eliminar termino en B
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}